name: Java CD with Gradle

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  EC2_USER: 'ec2-user'
  EC2_HOST: '3.112.41.87'
  SRC_PATH: 'build/libs/*.jar'
  DEST_PATH: '/home/ec2-user/student.management.jar'
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:

    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@v4
      - name: Grant permission for Gradlew
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Test with Gradle Wrapper
        run: ./gradlew test

      - name: Build with Gradle Wrapper
        run: ./gradlew bootJar

      - name: SCP Copy Application to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key $SRC_PATH $EC2_USER@$EC2_HOST:$DEST_PATH
      - name: SSH Application Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          envs: DEST_PATH,DB_HOST,DB_USERNAME,DB_PASSWORD
          script: |
            sudo yum update -y
            
            cat <<EOF | sudo tee /etc/sysconfig/student.management
            spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/student_management
            spring.datasource.username=${DB_USERNAME}
            spring.datasource.password=${DB_PASSWORD}

            EOF
            
            if [ -f /etc/systemd/system/student.management.service ]; then
              echo "already exists Service File"
            else
            cat <<EOL | sudo tee -a /etc/systemd/system/student.management.service
            [Unit]
            Description = student.management App
            
            [Service]
            ExecStart = java -jar ${DEST_PATH}
            EnvironmentFile = /etc/sysconfig/student.management
            Restart = no
            Type = simple
            User = ec2-user
            Group = ec2-user
            SuccessExitStatus = 143
            
            [Install]
            WantedBy = multi-user.target
            EOL
            fi
            
            sudo systemctl daemon-reload
            if sudo systemctl status student.management 2>&1 | grep "Active: active (running)" ; then
              sudo systemctl restart student.management
            else
              sudo systemctl start student.management
            fi